[package]
name = "messages_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
dashmap = "6.1.0"
futures = "0.3.31"
itertools = "0.14.0"
rand = "0.9.1"
reqwest = "0.12.18"
tokio = { version = "1.45.1", features = ["full"] }
